### ISSUE TITLE
Konsultacije 11.12.2024.

### ISSUE THREAD

**Issue by dmehanovic1** [dmehanovic1/apc_24-25_p3#1]
1.	Da li je potrebno, u sklopu projektnog zadatka, implementirati i komponentu Avalon-ST sučelja čiji će izlazni signali biti ulazni signali za GMII predajni interfejs, ili koristimo neku drugu opciju za generiranje relevantnih signala?
2.	Pretpostavka je da imamo jedan takt signal. Na koji način sinhronizujemo rad GMII modula, čiji takt mora biti 125 MHz, sa generatorom Ethernet okvira (Avalon-ST)?
3.	Referirajući se na odjeljak _Opis ulaznih i izlaznih signala_, te odjeljak _Logika rada modula_, da li imamo ispravno inicijalno konceptualno razumijevanje projektnog zadatka? Da li su u obzir uzeti svi neophodni ulazni i izlazni signali?
4.	Uzimamo li u obzir greške u prenosu podataka? Ako da, na koji način se indikacija greške sa Avalon-ST sučelja treba propagirati kroz logiku GMII predajnog interfejsa, te odraziti na indikaciju greške GMII predajnog interfejsa? Da li je potrebno zatražiti retransmisiju na neki način? Neovisno od potrebe, a interesa radi, da li se uopšte zahtjevi za retransmisijom implementiraju na ovom nivou (MAC <-> PHY)?
5.	Implementiramo li _backpressure_ mehanizam? Dakle, da li je potrebno kao izlazni signal sa GMII modula imati mogućnost slanja _ready_ signala, koji bi indicirao Avalon-ST komponenti da je GMII komponenta spremna za prihvat podataka?
6.	Interna manipulacija nad samim podacima unutar GMII modula, koji pristižu putem signala _avalon_data_, odnosi se isključivo na dodavanje preambule i SFD-a na primljeni podatak, pri čemu su i preambula i SFD konstante. Tačno/Netačno?

**Comment by eniokaljic** [comment]
1. Kompletan zadatak ćete implementirati unutar jedne komponente koja ima dva interfejsa: (1) ulazni Avalon-ST interfejs (tipa _sink_), te (2) izlazni GMII interfejs.
2. Kako na ulazu imate 64-bitnu _data_ magistralu, a na izlazu 8-bitnu, da bi zadržali isti _data rate_ biće potrebno generisati izvedeni takt signal za Avalon-ST interfejs čija je frekvencija 8 puta manja od frekvencije GMII takt signala. To znači da na ulaz dolazi poseban takt signal _(clock)_ sa frekvencijom 125 MHz. Taj isti takt signal prosljeđujete na izlaz kao GMII predajni takt _(gmii_tx_clk)._ Također, na osnovu ulaznog takt signala izvodite 8 puta sporiji Avalon-ST takt signal (_avalon_clock_) i također ga prosljeđujete na izlaz.
3. Signale _avalon_error_ i _gmii_txerr_ izbacite, da pojednostavimo zadatak. Također, na GMII interfejsu ne postoji _gmii_ready_ signal. Vaš sklop neće imati povratnu kontrolu toka _(backpressure)_. Logiku rada modula treba prikazati _waveform_ dijagramima, a ne opisno.
4. Odgovor dat pod 3.
5. Odgovor dat pod 3.
6. Preambula traje 7 bajt intervala, a SFD jedan. Biti sa GMII _data_ magistrale se prenose od LSB prema MSB, pa se onda preambula kodira kao 0x55, a SFD kao 0xD5. Podaci se kodiraju i prenose kao _big-endian_ (poznat i kao _network byte order_), tj. ako je odredišna MAC adresa AB:CD:EF:12:34:56, onda se prvo prenosi 0xAB, pa 0xCD i sve tako do 0x56.
